language: python
os:
  - linux
python:
  - 3.6 # only test on 3.6 and save notebook outputs on 3.6
sudo: false
install:
  - pip install -r requirements.txt
script:
  - cd examples
  - mkdir output
  - sh ./test.sh
notifications:
  email:
    recipients:
    - info@pvgeo.org
    on_success: never
    on_failure: never
